# Generated by Django 4.2 on 2025-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='position_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='position_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='position_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='position_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ko',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ko',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_uz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type_en',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type_ko',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type_ru',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fuel_type_uz',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_ko',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ko',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
