# Generated by Django 4.2 on 2025-07-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_feedback_comment_en_feedback_comment_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouractivitynumber',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ouractivitynumber',
            name='title_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ouractivitynumber',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ouractivitynumber',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
