# Generated by Django 4.2 on 2025-07-31 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_ouractivitynumber_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.URLField()),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_type_links', to='common.servicetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
