# Generated by Django 4.2 on 2024-11-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_product_image_productmedia_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('Home Page', 'Home Page'), ('About Us', 'About Us'), ('Projects', 'Projects'), ('News', 'News'), ('Sale', 'Sale'), ('Contact Us', 'Contact Us'), ('Our Services', 'Our Services')], max_length=100),
        ),
    ]
