# Generated by Django 4.2 on 2025-08-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_servicetypelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='tiktok_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='whatsup_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ServiceTypeLink',
        ),
    ]
