# Generated by Django 4.2 on 2024-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_remove_project_category_project_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner', models.ImageField(upload_to='common/project/banner/images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Project Banner',
                'verbose_name_plural': 'Project Banner',
            },
        ),
    ]
