# Generated by Django 4.2 on 2024-11-18 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_projectbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbanner',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='common.project'),
            preserve_default=False,
        ),
    ]
