# Generated by Django 4.2 on 2024-11-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_projectbanner_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectbanner',
            unique_together={('project', 'title')},
        ),
    ]
