# Generated by Django 4.2 on 2024-11-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_infocompany_product_main_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmedia',
            unique_together={('product', 'order')},
        ),
    ]
