# Generated by Django 4.2 on 2024-11-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_news_description_en_news_description_ko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='user_feedback_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_feedback_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_feedback_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_feedback_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_full_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_full_name_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_full_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_full_name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_role_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_role_ko',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_role_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='user_role_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
