# Generated by Django 4.2 on 2024-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_product_description_en_product_description_ko_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infocompany',
            options={'verbose_name': 'Info Company', 'verbose_name_plural': 'Info Company'},
        ),
        migrations.AlterModelOptions(
            name='ourinfo',
            options={'verbose_name': 'Our Info', 'verbose_name_plural': 'Our Info'},
        ),
        migrations.AddField(
            model_name='infocompany',
            name='customers_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infocompany',
            name='grateful_customers_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ourinfo',
            name='banner',
            field=models.ImageField(default='1', upload_to='common/product/banner/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourinfo',
            name='image1',
            field=models.ImageField(default='1', upload_to='common/product/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourinfo',
            name='image2',
            field=models.ImageField(default='1', upload_to='common/product/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ourinfo',
            name='image3',
            field=models.ImageField(default='1', upload_to='common/product/images/'),
            preserve_default=False,
        ),
    ]
