# Generated by Django 4.2 on 2024-11-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_infocompany_description_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactphonenumber',
            options={'verbose_name': 'Contact Phone Number', 'verbose_name_plural': 'Contact Phone Numbers'},
        ),
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'verbose_name': 'Customer Feedback', 'verbose_name_plural': 'Customer Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='infocompany',
            options={'verbose_name': 'Info Company', 'verbose_name_plural': 'Info Companies'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='projectbanner',
            options={'verbose_name': 'Project Banner', 'verbose_name_plural': 'Project Banners'},
        ),
        migrations.AlterModelOptions(
            name='usercontactapplication',
            options={'ordering': ['is_contacted'], 'verbose_name': 'Contact Application', 'verbose_name_plural': 'Contact Applications'},
        ),
    ]
